<?php


//  ___     _               _    _       ___      _
// |_ _|_ _| |_ ___ _ ___ _(_)__| |_ ___| _ ) ___| |_
//  | || ' \  _/ -_) '_\ V / (_-<  _/ -_) _ \/ _ \  _|
// |___|_||_\__\___|_|  \_/|_/__/\__\___|___/\___/\__|
// By Doppio - https://github.com/iDoppioclick


// Config file, enter here the information in order to make the bot work.


// General bot infos
// ----------------------------------------------------------------------

// Insert here the bot token generated by @BotFather.
$API = "INSERT_YOUR_TOKEN_HERE";

// Insert here the bot username, without the "@".
$BotUserName = "INSERT_HERE_THE_BOT_USERNAME";


// Database
// ----------------------------------------------------------------------

// Insert here the database name.
$DatabaseName = "INSERT_HERE_THE_DATABASE_NAME";

// Insert here the database username.
$DatabaseUsername = "INSERT_HERE_THE_DATABASE_USERNAME";

// Insert here the database user password.
$DatabasePassword = "INSERT_HERE_THE_DATABASE_USER_PASSWORD";